name: DeepSurv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - htop
  - poetry
  - cookiecutter
  - myst-nb
  - scalene
  - pip:
    - https://github.com/Lasagne/Lasagne/archive/master.zip

# conda env create -f conda_env_SurvivalScore.yml
